__default__:
    system: 'slurm'
    account: 122773337574
    time: "23:00:00" # in minutes
    mem: "40g" # in 40GB
    threads: "10"
    queue: "xlong" # gpu
    nodes: "1"


Prepare_reference:
    threads: "20"
    time: "1-10:00:00"


Trim_reads:
    threads: "20"

Build_rRNA_index:
    threads: "20"

Map_reads2rRNA:
    threads: "20"
    time: "3-00:00:00"

SortSam:
    threads: "20"

Remove_rRNA:
    threads: "20"

Estimate_abundance:
    threads: "20"
    time: "3-00:00:00" 
