ORGANISM: "Human"
FASTA: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.fna.gz" # "http://ftp.ensembl.org/pub/release-103/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.toplevel.fa.gz" #"http://ftp.ensembl.org/pub/release-103/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz" 
GTF: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gtf.gz"  #"http://ftp.ensembl.org/pub/release-103/gtf/homo_sapiens/Homo_sapiens.GRCh38.103.chr.gtf.gz" #"http://ftp.ensembl.org/pub/release-103/gtf/homo_sapiens/Homo_sapiens.GRCh38.103.gtf.gz"
SAMPLE_FILE: "config/sample.tsv"
SAMPLES: ["Control_A", "Control_B", "Control_C", "Control_D", 
         "Test_1A", "Test_1B", "Test_1C", 
         "Test_10A", "Test_10B", "Test_10C", "Test_10D"]
ALIGNER: "bowtie2" # "bowtie", "bowtie2", "star"

CONDA:  "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq"
DATABASE_NAME: "silva_DB"
# Large subunit rRNA
LSU_URL: "https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_138.1_LSURef_NR99_tax_silva.fasta.gz"
# Small subunit rRNA
SSU_URL: "https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_138.1_SSURef_NR99_tax_silva.fasta.gz"

PROJECT_DIR: "/scratch/user/obayomi/projects/transcriptomics/zymo"

# Full paths the specified programs
programs_path:
    multiqc: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/multiqc"
    trimmomatic: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/trimmomatic"
    bowtie:
        bowtie: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/bowtie2"
        build: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/bowtie2-build"
    samtools: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/samtools"
    fastqc: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/fastqc"
    rsem:
        prepare_reference: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/rsem-prepare-reference"
        calculate_expression: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/rsem-calculate-expression" 
        plot_model: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/rsem-plot-model"
        generate_matrix: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/bin/rsem-generate-data-matrix"
        

parameters:
    trimmomatic: 
        adaptors: "/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/share/trimmomatic-0.39-2/adapters/Truseq_and_Nextera-PE.fa"
        min_len: 30


# Full paths to your conda environments and their respective PERL5LIB directories
conda:
    non_model_RNA_Seq:
        env: "module purge; module load WebProxy Anaconda3/2020.07; set +u; source activate /scratch/user/obayomi/.conda/envs/non_model_RNA_Seq; set -u"
        perl5lib: "export PERL5LIB=/scratch/user/obayomi/.conda/envs/non_model_RNA_Seq/lib/site_perl/5.26.2/"

